### ISSUE TITLE
Broken Styles on Dropdown Component

### ISSUE THREAD

**Issue by sparty02** [react-toolbox/react-toolbox-themr#16]
[Repro here](https://github.com/sparty02/react-toolbox-demo).  Notice how the dropdown component doesn't have the styling as demonstrated [here](http://react-toolbox.com/#/components/dropdown).  From a quick glance, the cursor is always in the ```not-allowed``` state and the highlight on hover isn't working.

![screenshot](https://github.com/sparty02/react-toolbox-demo/raw/master/react-toolbox-themr-dropdown-issue.gif)

**Comment by javivelasco** [comment]
Hi! Thanks for reporting. 

The issue here is that we are setting some globals in the playground that makes the layout work properly in the first example. The `not-allowed` cursor was a [small bug](https://github.com/react-toolbox/react-toolbox/commit/cec890b1aadd5cf044919bb170c9b22db3f09451) with a selector.

If will be fixed with the next release, meanwhile you can write a custom **theme** object to override it and remove the cursor. For the layout of the first example to work you may check the globals in the playground and add them to your project.
