### ISSUE TITLE
README.md output path consistency

### ISSUE THREAD

**Issue by supirman** [react-toolbox/react-toolbox-themr#23]
Please make the output path to be consistent in example, so it easy to follow for beginer like me. 
It has 3 different value :  
- `public/react-toolbox` in gif 
- `assets/react-toolbox` in README config example 
- `src/toolbox` in `src/constants.js` default setting

**Comment by javivelasco** [comment]
The gif is outdated but its not worthy to re-record it just for the output path so I've added a note before it's shown in the README telling that the current output path is `src/toolbox`. In the README example it's ok because we are setting in the package: `"output": "assets/react-toolbox"`. If you omit the setting it defaults to `src/toolbox`
